### ISSUE TITLE
Verification on Plugin Portal

### ISSUE THREAD

**Issue by junichi11** [npetrovski/nbphar#1]
Hi, 

At first, Thanks for creating this plugin. It's very great!

It would be great if user can install this plugin from NetBeans IDE itself directly. So, could you sign nbm, then request verification on Plugin Portal?

BTW, probably nbproject/private directory should be ignored.

Thanks!

**Comment by npetrovski** [comment]
@junichi11 Thank you for the comments.

The plugin was uploaded and sent for validation few days ago (the signed version) and since yesterday it is already available @NetBeans official repository (http://plugins.netbeans.org/plugin/58816/nbphar).

I guess you will not see it within the NetBeans IDE until they refresh their own database.

Regarding nbproject/private - you are right - it will be added to the ignore list - I just uploaded the code before I made the publish request to netbeans.com so the source is available online.

Regards,
Nick

**Comment by junichi11** [comment]
> The plugin was uploaded and sent for validation few days ago (the signed version) and since yesterday it is already available @NetBeans official repository (http://plugins.netbeans.org/plugin/58816/nbphar).

Yep, I know it :)

> I guess you will not see it within the NetBeans IDE until they refresh their own database.

No, You have to click a request button. Could you confirm your plugin's page on PP?
![nbphar-verify-1](https://cloud.githubusercontent.com/assets/738383/8424808/252434c4-1f3a-11e5-864b-9bda28038c31.png)

If you do that, verification status is shown like the following:
![nbphar-verify-2](https://cloud.githubusercontent.com/assets/738383/8424815/43ce95d6-1f3a-11e5-9271-441ee73b046c.png)

Thanks,
Junichi

**Comment by npetrovski** [comment]
Thanks mate - will do so.

**Comment by junichi11** [comment]
:+1: Thanks a lot!
